Revert "Dockerfile: Combine ENV instructions into one"
This reverts commit 6af8f96428fc2ff32a3303cf1d29474fdbf5cf32.

Causes problems with ant during the build for some reason:

/bin/ant: 1: cd: can't cd to /bin/../share/ant/bin/..
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher